name: MLOps CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  mlops-pipeline:

    runs-on: ubuntu-latest

    steps:

      # ─────────────────────────────────────────────
      # Checkout Repository
      # ─────────────────────────────────────────────

      - name: Checkout repository

        uses: actions/checkout@v4

      # ─────────────────────────────────────────────
      # Setup Python
      # ─────────────────────────────────────────────

      - name: Set up Python

        uses: actions/setup-python@v5

        with:
          python-version: '3.11'

      # ─────────────────────────────────────────────
      # Install Dependencies
      # ─────────────────────────────────────────────

      - name: Install dependencies

        run: |

          python -m pip install --upgrade pip

          pip install -r requirements.txt

          pip install dvc[s3]

      # ─────────────────────────────────────────────
      # Configure AWS Credentials
      # ─────────────────────────────────────────────

      - name: Configure AWS Credentials

        uses: aws-actions/configure-aws-credentials@v4

        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}

          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      # ─────────────────────────────────────────────
      # Pull DVC Data
      # ─────────────────────────────────────────────

      - name: DVC Pull

        run: dvc pull

      # ─────────────────────────────────────────────
      # Run DVC Pipeline
      # ─────────────────────────────────────────────

      - name: Run DVC Pipeline

        run: dvc repro

      # ─────────────────────────────────────────────
      # Run Flask App Test
      # ─────────────────────────────────────────────

      - name: Test Flask App

        run: |

          python -m py_compile app/app.py

      # ─────────────────────────────────────────────
      # Docker Build Test
      # ─────────────────────────────────────────────

      - name: Build Docker Image

        run: docker build -t student-performance-ml .

      # ─────────────────────────────────────────────
      # Success Message
      # ─────────────────────────────────────────────

      - name: Pipeline Success

        run: echo "CI/CD Pipeline completed successfully!"
